# Nainstaluje vim, Pathogen, gruvbox
- name: Konfigurace Vimu
  hosts: localhost
  gather_facts: yes
  become: no

  vars:
    vim_dir: "{{ ansible_env.HOME  }}/.vim"
    vimrc: "{{ ansible_env.HOME  }}/.vimrc"
    bashrc: "{{ ansible_env.HOME }}/.bashrc"

  tasks:
    - name: Instalace Balicku
      package:
        name: "{{ item }}"
        state: present
      loop:
        - [ vim, git, mc, curl, wget ] 

    - name: Adresarova struktura
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0750
      loop:
        - "{{ vim_dir }}"
        - "{{ vim_dir }}/swap"
        - "{{ vim_dir }}/backup"
        - "{{ vim_dir }}/autoload"
        - "{{ vim_dir }}/bundle"

    - name: Pathogen pro instalaci doplnku
      get_url:
        dest: "{{ vim_dir }}/autoload/pathogen.vim"
        url: https://tpo.pe/pathogen.vim

    - name: Vim Pluginy
      git:
        dest: "{{ vim_dir }}/bundle/{{ item.name }}"
        repo: "{{ item.url }}"
        clone: yes
        update: yes
        recursive: no
      loop:
        - { name: gruvbox, url: https://github.com/morhetz/gruvbox.git }

    - name: .vimrc
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dst }}"
        backup: yes
        mode: 0640
      loop:
        - { src: "srcfiles/.bashrc", dst: "{{ bashrc }}", src: "srcfiles/.vimrc", dst: "{{ vimrc }}" }
